### ISSUE TITLE
希望大佬增加重温经典的v6源

### ISSUE THREAD

**Issue by xdfx1180** [fanmingming/live#250]
## 意见建议
请在此提出您的意见或建议。

**Comment by fanmingming** [comment]
感谢反馈，目前暂时还没有可用的重温经典频道IPv6源。

**Comment by bh10086** [comment]
能不能增加下新视觉体育呢，我都想掏钱买链接了

**Comment by fanmingming** [comment]
> 能不能增加下新视觉体育呢，我都想掏钱买链接了

目前贵州移动有IPv4的新视觉频道。http://39.136.18.179/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226188/1/index.m3u8?fmt=ts2hls

**Comment by fanmingming** [comment]
> ## 意见建议
> 请在此提出您的意见或建议。
重温经典IPv4源:
http://1.62.64.97/0b926d37065dc656266be75dd9d25565.v.smtcdns.net/zycfcdn.gdwlcloud.com/PLTV/88888888/224/3221225563/index.m3u8

**Comment by bh10086** [comment]
大哥搞个电报收费弄电源吧








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月19日(星期一) 晚上6:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fanmingming/live] 希望大佬增加重温经典的v6源 (Issue #250)





  
意见建议
 
请在此提出您的意见或建议。
 重温经典IPv4源:
 http://1.62.64.97/0b926d37065dc656266be75dd9d25565.v.smtcdns.net/zycfcdn.gdwlcloud.com/PLTV/88888888/224/3221225563/index.m3u8

**Comment by bh10086** [comment]
大佬v6的地址都失效了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 范明明 ***@***.***&gt;
发送时间: 2024年2月19日 21:33
收件人: fanmingming/live ***@***.***&gt;
抄送: bh10086 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [fanmingming/live] 希望大佬增加重温经典的v6源 (Issue #250)





  
大哥搞个电报收费弄电源吧
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年2月19日(星期一) 晚上6:37 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [fanmingming/live] 希望大佬增加重温经典的v6源 (Issue #250) 意见建议 请在此提出您的意见或建议。 重温经典IPv4源: http://1.62.64.97/0b926d37065dc656266be75dd9d25565.v.smtcdns.net/zycfcdn.gdwlcloud.com/PLTV/88888888/224/3221225563/index.m3u8 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
抱歉，主要是个人精力和时间有限。
 还有，感觉把网络上的资源拿来赚钱并不道德。😌
